image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-browser
tasks:
  - init: |
      npm ci
      npm run server:init
    command: |
      gp sync-done init
      export NODE_ENV=development
      export VSCODE_DEV=1
      npm run watch
    name: watch app
  - command: |
      export NODE_ENV=development
      export VSCODE_DEV=1
      gp sync-await init
      ./scripts/code-server.sh --without-connection-token
    name: run app
    openMode: split-right
  - name: Local Proxy
    command: |
      cd gitpod-proxy
      gp ports await 9888
      go run main.go

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - svelte.svelte-vscode
