// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt for license information.

namespace OpenVSCodeServer.Kestrel;

/// <summary>
/// Bridge between the OpenVSCode session manager and the parent application's source of truth for
/// workspace files. The library hands the implementation a freshly-created empty folder and
/// expects it to be populated with the workspace contents in <see cref="InitializeAsync"/>; when
/// the user saves files inside that folder (or when the session ends) the library calls
/// <see cref="SaveAsync"/> with the set of files that changed so the application can persist them
/// back to durable storage.
///
/// <para>Implementations are resolved from the DI container with <em>scoped</em> lifetime per
/// session — register via
/// <see cref="OpenVSCodeServerServiceCollectionExtensions.AddVSCodeFiles{T}"/>.</para>
/// </summary>
public interface IVSCodeFiles
{
	/// <summary>
	/// Populate <paramref name="context"/>.<see cref="VSCodeSessionContext.WorkspaceFolder"/> with
	/// the initial workspace contents. Called once per session, immediately after the folder is
	/// created and before the IDE URL is returned to the caller. The folder is guaranteed to
	/// exist and to be empty on entry.
	/// </summary>
	Task InitializeAsync(VSCodeSessionContext context, CancellationToken cancellationToken);

	/// <summary>
	/// Persist the supplied set of file changes back to durable storage. Called repeatedly during
	/// a session as the user saves files (debounced by
	/// <see cref="VSCodeSessionOptions.SaveDebounce"/>) and once more when the session is closed.
	/// Implementations should be idempotent — the same path may appear in multiple consecutive
	/// batches if the file is saved repeatedly. Paths are relative to
	/// <paramref name="context"/>.<see cref="VSCodeSessionContext.WorkspaceFolder"/> and always
	/// use forward slashes regardless of host OS.
	/// </summary>
	Task SaveAsync(
		VSCodeSessionContext context,
		IReadOnlyCollection<VSCodeFileChange> changes,
		CancellationToken cancellationToken);
}

/// <summary>
/// Identifying and contextual information for a single VS Code session. A new instance is created
/// for every <see cref="IVSCodeFiles"/> invocation and is safe to capture for the duration of the
/// call.
/// </summary>
public sealed class VSCodeSessionContext
{
	/// <summary>
	/// Opaque, URL-safe session identifier generated by the library.
	/// </summary>
	public required string SessionId { get; init; }

	/// <summary>
	/// Absolute path to the per-session temporary folder on disk. The folder is owned by the
	/// session manager and is removed when the session ends; consumers should treat it as a
	/// scratch area and rely on <see cref="IVSCodeFiles.SaveAsync"/> to persist changes.
	/// </summary>
	public required string WorkspaceFolder { get; init; }

	/// <summary>
	/// Caller-supplied metadata copied verbatim from the <c>state</c> property of the create-
	/// session request body. Useful for threading a tenant id, document id, or auth context from
	/// the HTTP layer down to the <see cref="IVSCodeFiles"/> implementation.
	/// </summary>
	public IReadOnlyDictionary<string, string> State { get; init; } =
		new Dictionary<string, string>(StringComparer.Ordinal);
}

/// <summary>
/// Describes a single file that changed inside a session's workspace folder.
/// </summary>
/// <param name="RelativePath">Path relative to the session's workspace folder, using forward
/// slashes. Never starts with a slash.</param>
/// <param name="Kind">Whether the file was created, modified, or deleted since the previous
/// <see cref="IVSCodeFiles.SaveAsync"/> call.</param>
public readonly record struct VSCodeFileChange(string RelativePath, VSCodeFileChangeKind Kind);

/// <summary>
/// The kind of change reported by the file watcher to <see cref="IVSCodeFiles.SaveAsync"/>.
/// </summary>
public enum VSCodeFileChangeKind
{
	/// <summary>The file did not exist at the start of the batch and exists now.</summary>
	Created,
	/// <summary>The file existed at the start of the batch and its contents changed.</summary>
	Modified,
	/// <summary>The file existed at the start of the batch and no longer exists.</summary>
	Deleted,
}
